### ISSUE TITLE
Capacitor3KakaoLogin 를 찾을 수 없습니다.

### ISSUE THREAD

**Issue by bbangkwan** [efluvi/capacitor3-kakao-login#2]
해당 plugin 설치 후 Capacitor3KakaoLogin 를 불러올 수 가 없습니다. 혹시 추가 설정이 필요할까요?

**Comment by bdhwan** [comment]
어느 플랫폼에서 불러올수가없으신가요?

**Comment by bbangkwan** [comment]
ionic + angular 에서 개발하고 있는데 angular에서 해당 plugin을 찾지 못합니다.

**Comment by bdhwan** [comment]
import { Capacitor3KakaoLogin } from 'capacitor3-kakao-login';

이렇게 임포트하면 나와야 정상입니다. 

아래 예제와 같이 
https://github.com/efluvi/capacitor3-kakao-login/blob/master/example-for-ionic/src/app/kakao.service.ts

example-for-ionic 프로젝트를 참고해주세요

**Comment by bbangkwan** [comment]
네 동일하게 했을 경우,
`TS7016: Could not find a declaration file for module 'capacitor3-kakao-login'. 'E:/public/1.itsgolf/1.dev/1-1.mobile_new/ItsGolfApp_capacitor/node_modules/capacitor3-kakao-login/dist/plugin.cjs.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/capacitor3-kakao-login` if it exists or add a new declaration (.d.ts) file containing `declare module 'capacitor3-kakao-login';``
와 같이 나옵니다.

![image](https://user-images.githubusercontent.com/8359656/154305515-168cc59b-18cc-42ec-a34a-0129c2991c79.png)

**Comment by bbangkwan** [comment]
네 예제 프로젝트를 다운받아서 확인해봤는데 동일한 에러가 발생합니다.

**Comment by bdhwan** [comment]
라이브러리 폴더에서 npm i && npm run build 를 한번 해보세요.
그래도 안된다면 저도 원인을 모르겠습니다

2022년 2월 17일 (목) 오후 9:41, bbangkwan ***@***.***>님이 작성:

**Comment by bbangkwan** [comment]
`"module": "src/index.ts",
  "types": "src/index.ts",
  "unpkg": "dist/plugin.js",
  "files": [
    "android/src/main/",
    "android/build.gradle",
    "src/",
    "ios/Plugin/",
    "Capacitor3KakaoLogin.podspec"
  ],`

위와 같이 수정을 해서 해당 이슈는 처리가 되었습니다.

다만, "ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'initializeKakao')
TypeError: Cannot read properties of undefined (reading 'initializeKakao')" 에러가 발생을 합니다. 혹시 이 부분은 어떻게 해결하면 좋을까요..??
