### ISSUE TITLE
ios 16 에서 오류발생합니다.

### ISSUE THREAD

**Issue by Nitid12** [efluvi/capacitor3-kakao-login#4]
xcode 업뎃 이후 아래 오류 발생하고 있습니다.

AuthController.swift:43:6: error build: Stored properties cannot be marked potentially unavailable with '@available'

xcode 14 , KakaoSDKAuth Pod 버전은 (2.10.1) 명시되어 있습니다.  

확인부탁 드립니다. 감사합니다.

**Comment by bdhwan** [comment]
0.0.11 버전에 수정하여 배포하였습니다!
